//! Canonical durable task record model.
//!
//! Field ownership follows `doc/architecture/durable-task-dispatch.md`
//! (Canonical Task Identity And Record). The structs here are the store
//! authority facts; physical storage schemas (Mongo DTO) are adapters over
//! this model. Identity types are reused from `skiff-artifact-model` /
//! `skiff-deployment` where the repo already owns the canonical form.

use std::fmt;

use serde::{Deserialize, Serialize};
use skiff_artifact_model::{
    ActorImplementationIdentity, ActorMethodIdentity, PackageCallableId,
    RecoverableExpectedTypePlan, RuntimeAssemblyRef, RuntimeConfigSnapshotRef,
    ServiceDeploymentRef,
};
use skiff_deployment::projection::actor_routing::ActorRoutingRef;

/// Opaque task identity. Generated by the submission side before the first
/// physical write; the store only persists and compares it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TaskId(String);

/// Opaque attempt identity. A fresh value is created on every successful claim.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct AttemptId(String);

/// Opaque lease identity. A fresh value is created on every successful claim.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct LeaseId(String);

/// Owner scope for a task. Status / cancel are only valid inside this scope;
/// the physical value is the authenticated service id projected by the task
/// control plane.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ServiceOwner(String);

impl TaskId {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn into_string(self) -> String {
        self.0
    }
}

impl AttemptId {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl LeaseId {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl ServiceOwner {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

macro_rules! as_str_impl {
    ($ty:ty) => {
        impl AsRef<str> for $ty {
            fn as_ref(&self) -> &str {
                self.as_str()
            }
        }

        impl From<String> for $ty {
            fn from(value: String) -> Self {
                Self::new(value)
            }
        }

        impl From<&str> for $ty {
            fn from(value: &str) -> Self {
                Self::new(value)
            }
        }

        impl fmt::Display for $ty {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str(self.as_str())
            }
        }
    };
}

as_str_impl!(TaskId);
as_str_impl!(AttemptId);
as_str_impl!(LeaseId);
as_str_impl!(ServiceOwner);

/// Canonical UTC epoch timestamp in milliseconds.
///
/// This is a durable, cross-host comparable timestamp, not a process-local
/// monotonic `Instant`. Due visibility, lease expiry and expiry races use the
/// TaskStore authority clock; this type only carries the durable value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct DurableUtcTimestamp(i64);

impl DurableUtcTimestamp {
    pub fn from_millis(millis: i64) -> Self {
        Self(millis)
    }

    pub fn millis(&self) -> i64 {
        self.0
    }

    pub fn checked_add_millis(self, millis: i64) -> Option<Self> {
        self.0.checked_add(millis).map(Self)
    }
}

impl fmt::Display for DurableUtcTimestamp {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}", self.0)
    }
}

/// Durable duration in milliseconds (e.g. terminal retention horizon).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct DurableDuration(i64);

impl DurableDuration {
    pub fn from_millis(millis: i64) -> Self {
        Self(millis)
    }

    pub fn millis(&self) -> i64 {
        self.0
    }
}

/// Canonical task state machine (authoritative design "State Machine").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TaskState {
    Scheduled,
    Ready,
    Leased,
    Succeeded,
    Failed,
    PlatformFailed,
    Canceled,
}

impl TaskState {
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            Self::Succeeded | Self::Failed | Self::PlatformFailed | Self::Canceled
        )
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Scheduled => "scheduled",
            Self::Ready => "ready",
            Self::Leased => "leased",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::PlatformFailed => "platformFailed",
            Self::Canceled => "canceled",
        }
    }
}

impl fmt::Display for TaskState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// One valid execution attempt lease. Fencing is lease-id based: every
/// settlement / heartbeat must carry the current lease id.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskLease {
    pub lease_id: LeaseId,
    pub attempt_id: AttemptId,
    pub owner: String,
    pub expiry: DurableUtcTimestamp,
}

/// Canonical terminal outcome. The terminal state is derived from the
/// outcome; identity of a settlement is `outcome` equality.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum TaskOutcome {
    /// Target returned normally.
    Succeeded,
    /// Target explicitly threw / rejected.
    TargetFailed { error: String },
    /// Platform proved the task can never form a legal execution attempt.
    PlatformFailed { reason: String },
    /// Before-start cancellation converged.
    Canceled,
}

impl TaskOutcome {
    pub fn terminal_state(&self) -> TaskState {
        match self {
            Self::Succeeded => TaskState::Succeeded,
            Self::TargetFailed { .. } => TaskState::Failed,
            Self::PlatformFailed { .. } => TaskState::PlatformFailed,
            Self::Canceled => TaskState::Canceled,
        }
    }
}

/// Durable terminal record written by one settlement CAS.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskTerminal {
    pub settled_at: DurableUtcTimestamp,
    pub outcome: TaskOutcome,
}

impl TaskTerminal {
    pub fn state(&self) -> TaskState {
        self.outcome.terminal_state()
    }

    pub fn same_outcome(&self, other: &Self) -> bool {
        self.outcome == other.outcome
    }
}

/// Trace correlation inherited from the submitting request. Attempt / request
/// spans are created by the execution layer, not owned by the store.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskTraceContext {
    pub trace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub span_id: Option<String>,
}

/// Frozen execution image facts (authoritative design "Execution Image And
/// Target Pinning"). The store treats this as an immutable, authenticated
/// reference; it never resolves "latest" at execution time.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TaskExecutionImageRef {
    pub target_environment: String,
    pub package_version: String,
    pub assembly: RuntimeAssemblyRef,
    pub config_snapshot: RuntimeConfigSnapshotRef,
    pub deployment: ServiceDeploymentRef,
}

/// Already-encoded recoverable payload bytes. The store is deliberately
/// payload-agnostic: decode uses the execution image's linked expected plan at
/// attempt time and is owned by the execution layer.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct RecoverablePayload(Vec<u8>);

impl RecoverablePayload {
    pub fn new(bytes: Vec<u8>) -> Self {
        Self(bytes)
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    pub fn into_bytes(self) -> Vec<u8> {
        self.0
    }
}

/// Frozen actor activation facts needed to recover a minimal registry entry
/// and run `create` when no live incarnation exists.
#[derive(Debug, Clone, PartialEq)]
pub struct ActorActivationSnapshot {
    pub key: RecoverablePayload,
    pub create_input: RecoverablePayload,
    /// Artifact-form expected-type plan for the frozen create input (store
    /// witness). Execution decodes against linked expected plans, never this
    /// projection.
    pub expected_type_plan: RecoverableExpectedTypePlan,
    /// Runtime-form recoverable expected-type plan as frozen by the
    /// submission side (E2a wire `expectedTypePlan`). The runtime form is the
    /// only plan the Runtime can freeze from the linked program; the artifact
    /// projection above is a store-compatible witness. `None` for records
    /// created before this field existed (C1 compatibility).
    pub expected_type_plan_runtime: Option<serde_json::Value>,
}

/// Store-model projection of the actor declaration owner coordinates
/// (`ActorDeclarationOwnerFrameHeader` wire shape). Needed by
/// get-or-activate branch 3: restoring a minimal registry entry after Router
/// restart requires the exact declaration owner so the owner Runtime can
/// resolve the linked actor declaration and run `create`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActorDeclarationOwner {
    pub unit: ActorDeclarationOwnerUnit,
    pub file: ActorDeclarationOwnerFile,
    pub actor_symbol: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    content = "value",
    rename_all = "camelCase",
    deny_unknown_fields
)]
pub enum ActorDeclarationOwnerUnit {
    Service,
    Package(u64),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    content = "value",
    rename_all = "camelCase",
    deny_unknown_fields
)]
pub enum ActorDeclarationOwnerFile {
    LoadedFileIndex(u64),
    FileIrIdentity(String),
}

/// Canonical detached-call target.
#[derive(Debug, Clone, PartialEq)]
pub enum DetachedCallTarget {
    Function {
        callable: PackageCallableId,
    },
    ActorMethod {
        actor: ActorRoutingRef,
        activation: ActorActivationSnapshot,
        implementation: ActorImplementationIdentity,
        method: ActorMethodIdentity,
        declaration_owner: ActorDeclarationOwner,
    },
}

/// Canonical task record. Field ownership follows the authoritative design;
/// all transitions are conditional writes against this record.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskRecord {
    pub task_id: TaskId,
    pub owner: ServiceOwner,
    pub execution: TaskExecutionImageRef,
    pub target: DetachedCallTarget,
    pub payload: RecoverablePayload,
    pub due_at: DurableUtcTimestamp,
    pub state: TaskState,
    pub attempt_generation: u64,
    pub active_lease: Option<TaskLease>,
    pub terminal: Option<TaskTerminal>,
    pub trace: TaskTraceContext,
    pub created_at: DurableUtcTimestamp,
    /// Scheduler-owned platform backoff: when set, no new attempt may be
    /// claimed before this durable store-authority timestamp. It is written
    /// atomically by lease-expiry recovery and provable-rejection release;
    /// submission leaves it `None`, and `claim` does not clear it (a past
    /// value is inert). It is not a user-facing retry policy.
    pub retry_not_before: Option<DurableUtcTimestamp>,
    /// Test-case authority captured at submission (F2a). When present the
    /// task attempt is a derived request of the parent test case: it carries
    /// the same opaque capability and test-effects-enabled admission, and it
    /// must execute on the exact origin Runtime connection with the parent
    /// service. Ordinary production tasks leave this `None` and keep the
    /// location-transparent scheduler semantics unchanged.
    pub test_case: Option<TaskTestCaseAuthority>,
}

/// Router-derived test-case authority persisted with one task record.
///
/// The wire `task.submit.request` deliberately carries only `callerRequestId`
/// (never the capability or parent id); the Router derives these facts from
/// the still-active parent request / Actor invocation on the exact same
/// Runtime connection. Durable attempts later re-enter the case through the
/// same capability, and admission enforces the origin connection / service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskTestCaseAuthority {
    /// Opaque Router-issued test case capability (test-runner-runtime
    /// isolation contract; never a Skiff value or business effect API).
    pub test_case_capability: String,
    /// Active parent request / Actor invocation id that submitted the task.
    pub parent_request_id: String,
    /// Exact origin Runtime replica that submitted the task.
    pub origin_runtime_id: String,
    /// Exact origin WebSocket connection generation on that replica.
    pub origin_connection_generation: u64,
}

impl TaskRecord {
    /// Initial-record validation for `create`: a task enters the store as
    /// `scheduled` with no lease / terminal and generation zero.
    pub fn validate_create(&self) -> Result<(), String> {
        if self.state != TaskState::Scheduled {
            return Err(format!(
                "task {} must be created in scheduled state, found {}",
                self.task_id, self.state
            ));
        }
        if self.attempt_generation != 0 {
            return Err(format!(
                "task {} must start with attempt generation 0",
                self.task_id
            ));
        }
        if self.active_lease.is_some() {
            return Err(format!(
                "task {} cannot be created with an active lease",
                self.task_id
            ));
        }
        if self.terminal.is_some() {
            return Err(format!(
                "task {} cannot be created with a terminal",
                self.task_id
            ));
        }
        if self.created_at.millis() < 0 || self.due_at.millis() < 0 {
            return Err(format!(
                "task {} timestamps must be non-negative epoch millis",
                self.task_id
            ));
        }
        Ok(())
    }

    pub fn status_kind(&self) -> TaskStatusKind {
        match self.state {
            TaskState::Scheduled => TaskStatusKind::Scheduled,
            TaskState::Ready => TaskStatusKind::Ready,
            TaskState::Leased => TaskStatusKind::Running,
            TaskState::Succeeded => TaskStatusKind::Succeeded,
            TaskState::Failed => TaskStatusKind::Failed,
            TaskState::PlatformFailed => TaskStatusKind::PlatformFailed,
            TaskState::Canceled => TaskStatusKind::Canceled,
        }
    }
}

/// Public `std.task.status` kind spelling (`doc/reference/dispatch.md` §3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TaskStatusKind {
    Scheduled,
    Ready,
    Running,
    Succeeded,
    Failed,
    PlatformFailed,
    Canceled,
    Expired,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskStatus {
    pub kind: TaskStatusKind,
}

/// Public `std.task.cancel` result kind spelling (`doc/reference/dispatch.md` §3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TaskCancelResultKind {
    Canceled,
    AlreadyStarted,
    AlreadyTerminal,
    Expired,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskCancelResult {
    pub kind: TaskCancelResultKind,
}

/// Platform error classification entry: permanent errors converge to terminal
/// `platform-failed`; transient errors keep the TaskId and are retried with
/// bounded backoff by the scheduler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlatformErrorClass {
    Permanent,
    Transient,
}

impl PlatformErrorClass {
    pub fn permanent() -> Self {
        Self::Permanent
    }

    pub fn transient() -> Self {
        Self::Transient
    }

    pub fn is_permanent(&self) -> bool {
        matches!(self, Self::Permanent)
    }

    /// Returns the terminal outcome for permanent errors; transient errors
    /// do not converge and must not be settled as terminal.
    pub fn terminal_outcome(self, reason: impl Into<String>) -> Option<TaskOutcome> {
        match self {
            Self::Permanent => Some(TaskOutcome::PlatformFailed {
                reason: reason.into(),
            }),
            Self::Transient => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_kinds_match_reference_spelling() {
        for kind in [
            TaskStatusKind::Scheduled,
            TaskStatusKind::Ready,
            TaskStatusKind::Running,
            TaskStatusKind::Succeeded,
            TaskStatusKind::Failed,
            TaskStatusKind::PlatformFailed,
            TaskStatusKind::Canceled,
            TaskStatusKind::Expired,
        ] {
            let value = serde_json::to_value(TaskStatus { kind }).expect("serialize");
            assert_eq!(value["kind"], serde_json::json!(kind_name(kind)));
        }
        for kind in [
            TaskCancelResultKind::Canceled,
            TaskCancelResultKind::AlreadyStarted,
            TaskCancelResultKind::AlreadyTerminal,
            TaskCancelResultKind::Expired,
        ] {
            let value = serde_json::to_value(TaskCancelResult { kind }).expect("serialize");
            assert_eq!(value["kind"], serde_json::json!(cancel_kind_name(kind)));
        }
    }

    fn kind_name(kind: TaskStatusKind) -> &'static str {
        match kind {
            TaskStatusKind::Scheduled => "scheduled",
            TaskStatusKind::Ready => "ready",
            TaskStatusKind::Running => "running",
            TaskStatusKind::Succeeded => "succeeded",
            TaskStatusKind::Failed => "failed",
            TaskStatusKind::PlatformFailed => "platformFailed",
            TaskStatusKind::Canceled => "canceled",
            TaskStatusKind::Expired => "expired",
        }
    }

    fn cancel_kind_name(kind: TaskCancelResultKind) -> &'static str {
        match kind {
            TaskCancelResultKind::Canceled => "canceled",
            TaskCancelResultKind::AlreadyStarted => "alreadyStarted",
            TaskCancelResultKind::AlreadyTerminal => "alreadyTerminal",
            TaskCancelResultKind::Expired => "expired",
        }
    }

    #[test]
    fn platform_error_classification_converges_only_permanent_errors() {
        let permanent = PlatformErrorClass::permanent();
        assert!(permanent.is_permanent());
        let outcome = permanent
            .terminal_outcome("execution record deleted")
            .expect("permanent converges");
        assert_eq!(outcome.terminal_state(), TaskState::PlatformFailed);

        let transient = PlatformErrorClass::transient();
        assert!(!transient.is_permanent());
        assert_eq!(
            transient.terminal_outcome("runtime unavailable"),
            None,
            "transient errors must not converge to terminal"
        );
    }

    #[test]
    fn task_state_ascii_spelling_is_stable() {
        assert_eq!(TaskState::Scheduled.as_str(), "scheduled");
        assert_eq!(TaskState::Ready.as_str(), "ready");
        assert_eq!(TaskState::Leased.as_str(), "leased");
        assert_eq!(TaskState::Succeeded.as_str(), "succeeded");
        assert_eq!(TaskState::Failed.as_str(), "failed");
        assert_eq!(TaskState::PlatformFailed.as_str(), "platformFailed");
        assert_eq!(TaskState::Canceled.as_str(), "canceled");
        assert!(TaskState::Succeeded.is_terminal());
        assert!(TaskState::Failed.is_terminal());
        assert!(TaskState::PlatformFailed.is_terminal());
        assert!(TaskState::Canceled.is_terminal());
        assert!(!TaskState::Scheduled.is_terminal());
        assert!(!TaskState::Ready.is_terminal());
        assert!(!TaskState::Leased.is_terminal());
    }
}
