// @generated by skiff-compiler platform-error-projections; DO NOT EDIT.

use std::fmt;

use serde::{de::DeserializeOwned, Deserialize, Deserializer, Serialize};
use skiff_artifact_model::platform_error_projection::{
    platform_error_projection_descriptor, PlatformErrorProjectionKey,
};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdActorActivationTimeoutErrorPayload {
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdActorMethodInvocationTimeoutErrorPayload {
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdBytesDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdCollectionArrayIndexOutOfBoundsErrorPayload {
    #[serde(rename = "index")]
    pub index: i64,
    #[serde(rename = "length")]
    pub length: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdCollectionJsonObjectPropertyNotFoundErrorPayload {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdCollectionMapKeyNotFoundErrorPayload {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdDbConflictErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "retryable")]
    pub retryable: bool,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdDbConstraintErrorPayload {
    #[serde(rename = "collection")]
    pub collection: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "packageId")]
    pub package_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdDbDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdErrorInstructionLimitExceededErrorPayload {
    #[serde(rename = "instructionCount")]
    pub instruction_count: i64,
    #[serde(rename = "limit")]
    pub limit: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdErrorTimeoutErrorPayload {
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdFileFileErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdHttpHttpErrorPayload {
    #[serde(rename = "detail")]
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub detail: Option<serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdHttpRequestTimeoutErrorPayload {
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdJsonDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdNumberDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdServiceProtocolErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdServiceProviderUnavailableErrorPayload {
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StdTimeDecodeErrorPayload {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "target")]
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", deny_unknown_fields)]
pub enum StdWebsocketWebSocketRequestErrorPayload {
    #[serde(rename = "connectionUnavailable")]
    ConnectionUnavailable {
        #[serde(rename = "message")]
        pub message: String,
    },
    #[serde(rename = "transportUnavailable")]
    TransportUnavailable {
        #[serde(rename = "message")]
        pub message: String,
    },
    #[serde(rename = "protocolError")]
    ProtocolError {
        #[serde(rename = "message")]
        pub message: String,
    },
    #[serde(rename = "resourceLimit")]
    ResourceLimit {
        #[serde(rename = "message")]
        pub message: String,
    },
    #[serde(rename = "remote")]
    Remote {
        #[serde(rename = "code")]
        pub code: i64,
        #[serde(rename = "data")]
        #[serde(deserialize_with = "deserialize_required_nullable")]
        pub data: Option<serde_json::Value>,
        #[serde(rename = "message")]
        pub message: String,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum PlatformErrorProjectionPayload {
    ConfigDecodeError(ConfigDecodeErrorPayload),
    StdActorActivationTimeoutError(StdActorActivationTimeoutErrorPayload),
    StdActorMethodInvocationTimeoutError(StdActorMethodInvocationTimeoutErrorPayload),
    StdBytesDecodeError(StdBytesDecodeErrorPayload),
    StdCollectionArrayIndexOutOfBoundsError(StdCollectionArrayIndexOutOfBoundsErrorPayload),
    StdCollectionJsonObjectPropertyNotFoundError(
        StdCollectionJsonObjectPropertyNotFoundErrorPayload,
    ),
    StdCollectionMapKeyNotFoundError(StdCollectionMapKeyNotFoundErrorPayload),
    StdDbConflictError(StdDbConflictErrorPayload),
    StdDbConstraintError(StdDbConstraintErrorPayload),
    StdDbDecodeError(StdDbDecodeErrorPayload),
    StdErrorInstructionLimitExceededError(StdErrorInstructionLimitExceededErrorPayload),
    StdErrorTimeoutError(StdErrorTimeoutErrorPayload),
    StdFileFileError(StdFileFileErrorPayload),
    StdHttpHttpError(StdHttpHttpErrorPayload),
    StdHttpRequestTimeoutError(StdHttpRequestTimeoutErrorPayload),
    StdJsonDecodeError(StdJsonDecodeErrorPayload),
    StdNumberDecodeError(StdNumberDecodeErrorPayload),
    StdServiceProtocolError(StdServiceProtocolErrorPayload),
    StdServiceProviderUnavailableError(StdServiceProviderUnavailableErrorPayload),
    StdTimeDecodeError(StdTimeDecodeErrorPayload),
    StdWebsocketWebSocketRequestError(StdWebsocketWebSocketRequestErrorPayload),
}

impl PlatformErrorProjectionPayload {
    pub const fn key(&self) -> PlatformErrorProjectionKey {
        match self {
            Self::ConfigDecodeError(_) => PlatformErrorProjectionKey::ConfigDecodeError,
            Self::StdActorActivationTimeoutError(_) => {
                PlatformErrorProjectionKey::StdActorActivationTimeoutError
            }
            Self::StdActorMethodInvocationTimeoutError(_) => {
                PlatformErrorProjectionKey::StdActorMethodInvocationTimeoutError
            }
            Self::StdBytesDecodeError(_) => PlatformErrorProjectionKey::StdBytesDecodeError,
            Self::StdCollectionArrayIndexOutOfBoundsError(_) => {
                PlatformErrorProjectionKey::StdCollectionArrayIndexOutOfBoundsError
            }
            Self::StdCollectionJsonObjectPropertyNotFoundError(_) => {
                PlatformErrorProjectionKey::StdCollectionJsonObjectPropertyNotFoundError
            }
            Self::StdCollectionMapKeyNotFoundError(_) => {
                PlatformErrorProjectionKey::StdCollectionMapKeyNotFoundError
            }
            Self::StdDbConflictError(_) => PlatformErrorProjectionKey::StdDbConflictError,
            Self::StdDbConstraintError(_) => PlatformErrorProjectionKey::StdDbConstraintError,
            Self::StdDbDecodeError(_) => PlatformErrorProjectionKey::StdDbDecodeError,
            Self::StdErrorInstructionLimitExceededError(_) => {
                PlatformErrorProjectionKey::StdErrorInstructionLimitExceededError
            }
            Self::StdErrorTimeoutError(_) => PlatformErrorProjectionKey::StdErrorTimeoutError,
            Self::StdFileFileError(_) => PlatformErrorProjectionKey::StdFileFileError,
            Self::StdHttpHttpError(_) => PlatformErrorProjectionKey::StdHttpHttpError,
            Self::StdHttpRequestTimeoutError(_) => {
                PlatformErrorProjectionKey::StdHttpRequestTimeoutError
            }
            Self::StdJsonDecodeError(_) => PlatformErrorProjectionKey::StdJsonDecodeError,
            Self::StdNumberDecodeError(_) => PlatformErrorProjectionKey::StdNumberDecodeError,
            Self::StdServiceProtocolError(_) => PlatformErrorProjectionKey::StdServiceProtocolError,
            Self::StdServiceProviderUnavailableError(_) => {
                PlatformErrorProjectionKey::StdServiceProviderUnavailableError
            }
            Self::StdTimeDecodeError(_) => PlatformErrorProjectionKey::StdTimeDecodeError,
            Self::StdWebsocketWebSocketRequestError(_) => {
                PlatformErrorProjectionKey::StdWebsocketWebSocketRequestError
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EncodedPlatformErrorProjectionPayload {
    projection_key: PlatformErrorProjectionKey,
    entry_fingerprint: &'static str,
    canonical_payload: Vec<u8>,
}

impl EncodedPlatformErrorProjectionPayload {
    pub const fn projection_key(&self) -> PlatformErrorProjectionKey {
        self.projection_key
    }

    pub const fn entry_fingerprint(&self) -> &'static str {
        self.entry_fingerprint
    }

    pub fn canonical_payload(&self) -> &[u8] {
        &self.canonical_payload
    }

    pub fn into_canonical_payload(self) -> Vec<u8> {
        self.canonical_payload
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum PlatformErrorProjectionDecodeOutcome {
    Known(PlatformErrorProjectionPayload),
    UnknownValid,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlatformErrorProjectionCodecError {
    Serialization {
        projection_key: PlatformErrorProjectionKey,
        message: String,
    },
    MalformedKnownPayload {
        projection_key: PlatformErrorProjectionKey,
        message: String,
    },
    NonCanonicalKnownPayload {
        projection_key: PlatformErrorProjectionKey,
    },
}

impl fmt::Display for PlatformErrorProjectionCodecError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Serialization {
                projection_key,
                message,
            } => write!(
                formatter,
                "failed to encode known platform projection {projection_key}: {message}"
            ),
            Self::MalformedKnownPayload {
                projection_key,
                message,
            } => write!(
                formatter,
                "malformed known platform projection {projection_key}: {message}"
            ),
            Self::NonCanonicalKnownPayload { projection_key } => write!(
                formatter,
                "known platform projection {projection_key} payload is not canonical JSON"
            ),
        }
    }
}

impl std::error::Error for PlatformErrorProjectionCodecError {}

pub fn encode_platform_error_projection_payload(
    payload: &PlatformErrorProjectionPayload,
) -> Result<EncodedPlatformErrorProjectionPayload, PlatformErrorProjectionCodecError> {
    let projection_key = payload.key();
    let canonical_payload = match payload {
        PlatformErrorProjectionPayload::ConfigDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdActorActivationTimeoutError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdActorMethodInvocationTimeoutError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdBytesDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdCollectionArrayIndexOutOfBoundsError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdCollectionJsonObjectPropertyNotFoundError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdCollectionMapKeyNotFoundError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdDbConflictError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdDbConstraintError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdDbDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdErrorInstructionLimitExceededError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdErrorTimeoutError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdFileFileError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdHttpHttpError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdHttpRequestTimeoutError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdJsonDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdNumberDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdServiceProtocolError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdServiceProviderUnavailableError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdTimeDecodeError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
        PlatformErrorProjectionPayload::StdWebsocketWebSocketRequestError(payload) => {
            encode_typed_payload(projection_key, payload)?
        }
    };
    let descriptor = platform_error_projection_descriptor(projection_key);
    Ok(EncodedPlatformErrorProjectionPayload {
        projection_key,
        entry_fingerprint: descriptor.entry_fingerprint(),
        canonical_payload,
    })
}

pub fn decode_platform_error_projection_payload(
    projection_key: &str,
    entry_fingerprint: &str,
    raw_payload: &[u8],
) -> Result<PlatformErrorProjectionDecodeOutcome, PlatformErrorProjectionCodecError> {
    let Ok(key) = PlatformErrorProjectionKey::parse_strict(projection_key) else {
        return Ok(PlatformErrorProjectionDecodeOutcome::UnknownValid);
    };
    let descriptor = platform_error_projection_descriptor(key);
    if entry_fingerprint != descriptor.entry_fingerprint() {
        return Ok(PlatformErrorProjectionDecodeOutcome::UnknownValid);
    }
    materialize_platform_error_projection_payload(key, raw_payload)
        .map(PlatformErrorProjectionDecodeOutcome::Known)
}

fn materialize_platform_error_projection_payload(
    projection_key: PlatformErrorProjectionKey,
    raw_payload: &[u8],
) -> Result<PlatformErrorProjectionPayload, PlatformErrorProjectionCodecError> {
    match projection_key {
        PlatformErrorProjectionKey::ConfigDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::ConfigDecodeError)
        }
        PlatformErrorProjectionKey::StdActorActivationTimeoutError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdActorActivationTimeoutError)
        }
        PlatformErrorProjectionKey::StdActorMethodInvocationTimeoutError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdActorMethodInvocationTimeoutError)
        }
        PlatformErrorProjectionKey::StdBytesDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdBytesDecodeError)
        }
        PlatformErrorProjectionKey::StdCollectionArrayIndexOutOfBoundsError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdCollectionArrayIndexOutOfBoundsError)
        }
        PlatformErrorProjectionKey::StdCollectionJsonObjectPropertyNotFoundError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdCollectionJsonObjectPropertyNotFoundError)
        }
        PlatformErrorProjectionKey::StdCollectionMapKeyNotFoundError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdCollectionMapKeyNotFoundError)
        }
        PlatformErrorProjectionKey::StdDbConflictError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdDbConflictError)
        }
        PlatformErrorProjectionKey::StdDbConstraintError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdDbConstraintError)
        }
        PlatformErrorProjectionKey::StdDbDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdDbDecodeError)
        }
        PlatformErrorProjectionKey::StdErrorInstructionLimitExceededError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdErrorInstructionLimitExceededError)
        }
        PlatformErrorProjectionKey::StdErrorTimeoutError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdErrorTimeoutError)
        }
        PlatformErrorProjectionKey::StdFileFileError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdFileFileError)
        }
        PlatformErrorProjectionKey::StdHttpHttpError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdHttpHttpError)
        }
        PlatformErrorProjectionKey::StdHttpRequestTimeoutError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdHttpRequestTimeoutError)
        }
        PlatformErrorProjectionKey::StdJsonDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdJsonDecodeError)
        }
        PlatformErrorProjectionKey::StdNumberDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdNumberDecodeError)
        }
        PlatformErrorProjectionKey::StdServiceProtocolError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdServiceProtocolError)
        }
        PlatformErrorProjectionKey::StdServiceProviderUnavailableError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdServiceProviderUnavailableError)
        }
        PlatformErrorProjectionKey::StdTimeDecodeError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdTimeDecodeError)
        }
        PlatformErrorProjectionKey::StdWebsocketWebSocketRequestError => {
            decode_typed_payload(projection_key, raw_payload)
                .map(PlatformErrorProjectionPayload::StdWebsocketWebSocketRequestError)
        }
    }
}

fn encode_typed_payload<T: Serialize>(
    projection_key: PlatformErrorProjectionKey,
    payload: &T,
) -> Result<Vec<u8>, PlatformErrorProjectionCodecError> {
    canonical_json_bytes(payload).map_err(|message| {
        PlatformErrorProjectionCodecError::Serialization {
            projection_key,
            message,
        }
    })
}

fn decode_typed_payload<T: DeserializeOwned + Serialize>(
    projection_key: PlatformErrorProjectionKey,
    raw_payload: &[u8],
) -> Result<T, PlatformErrorProjectionCodecError> {
    let payload = serde_json::from_slice::<T>(raw_payload).map_err(|error| {
        PlatformErrorProjectionCodecError::MalformedKnownPayload {
            projection_key,
            message: error.to_string(),
        }
    })?;
    let canonical = encode_typed_payload(projection_key, &payload)?;
    if canonical != raw_payload {
        return Err(PlatformErrorProjectionCodecError::NonCanonicalKnownPayload { projection_key });
    }
    Ok(payload)
}

fn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}

fn canonical_json_bytes<T: Serialize>(value: &T) -> Result<Vec<u8>, String> {
    skiff_canonical_json::canonical_json_bytes(value).map_err(|error| error.to_string())
}
