[package]
name = "skiff-runtime-bytecode-verifier"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0"
skiff-artifact-model = { path = "../../artifact-model" }
skiff-canonical-json = { path = "../../canonical-json" }
skiff-runtime-deployment-image = { path = "../deployment-image" }
skiff-runtime-linked-bytecode = { path = "../linked-bytecode" }
skiff-runtime-loader = { path = "../loader" }
skiff-runtime-model = { path = "../model" }

[dev-dependencies]
anyhow = "1.0"
skiff-artifact-identity = { path = "../../artifact-identity" }

[lints]
workspace = true
