[package]
name = "skiff-runtime-vm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
skiff-artifact-model = { path = "../../artifact-model" }
skiff-runtime-bytecode-verifier = { path = "../bytecode-verifier" }
skiff-runtime-deployment-image = { path = "../deployment-image" }
skiff-runtime-linked-bytecode = { path = "../linked-bytecode" }
skiff-runtime-model = { path = "../model" }

[lints]
workspace = true
