use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use skiff_compiler_input::CompilerPlatformSources;
use skiff_compiler_source::{
    resolve_platform_error_projection_catalog, ResolvedPlatformErrorProjectionCatalog,
};
use thiserror::Error;

mod fingerprint;
mod render_artifact_model;
mod render_request_contract;
mod rust_names;

use fingerprint::fingerprint_catalog;
use render_artifact_model::render_artifact_model;
use render_request_contract::render_request_contract;

const ARTIFACT_MODEL_OUTPUT: &str = "artifact-model/src/platform_error_projection/generated.rs";
const REQUEST_CONTRACT_OUTPUT: &str =
    "runtime/request-contract/src/platform_error_projection/generated.rs";
const GENERATED_HEADER: &str =
    "// @generated by skiff-compiler platform-error-projections; DO NOT EDIT.";
static TEMP_FILE_SEQUENCE: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlatformErrorProjectionCodegenAction {
    Generate,
    Check,
}

#[derive(Debug, Error)]
pub enum PlatformErrorProjectionCodegenError {
    #[error(transparent)]
    PlatformSources(#[from] skiff_compiler_input::CompilerPlatformSourcesError),
    #[error(transparent)]
    Catalog(#[from] skiff_compiler_source::PlatformErrorProjectionCatalogError),
    #[error("invalid resolved platform error projection catalog: {0}")]
    InvalidCatalog(String),
    #[error("failed to render platform error projections: {0}")]
    Render(String),
    #[error("generated output path escapes canonical repository root: {path}")]
    OutputEscapesRepository { path: PathBuf },
    #[error("generated output path is not a regular file: {path}")]
    OutputNotRegularFile { path: PathBuf },
    #[error("failed to access generated output {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("generated output is missing: {path}")]
    Missing { path: PathBuf },
    #[error("generated output has drifted: {path}")]
    Drift { path: PathBuf },
    #[error("failed to roll back generated outputs after publication failed: {0}")]
    Rollback(String),
}

struct RenderedOutput {
    relative_path: &'static str,
    bytes: Vec<u8>,
}

struct PreparedOutput {
    target: PathBuf,
    bytes: Vec<u8>,
    staged: Option<PathBuf>,
    backup: Option<PathBuf>,
    existed: bool,
    published: bool,
}

pub fn run_platform_error_projection_codegen(
    action: PlatformErrorProjectionCodegenAction,
    repository_root: &Path,
) -> Result<(), PlatformErrorProjectionCodegenError> {
    let platform_sources = CompilerPlatformSources::new(repository_root)?;
    let catalog = resolve_platform_error_projection_catalog(&platform_sources)?;
    let rendered = render_all(&catalog)?;
    match action {
        PlatformErrorProjectionCodegenAction::Generate => {
            generate_outputs(platform_sources.root(), rendered)
        }
        PlatformErrorProjectionCodegenAction::Check => {
            check_outputs(platform_sources.root(), &rendered)
        }
    }
}

fn render_all(
    catalog: &ResolvedPlatformErrorProjectionCatalog,
) -> Result<Vec<RenderedOutput>, PlatformErrorProjectionCodegenError> {
    let fingerprinted = fingerprint_catalog(catalog)?;
    let artifact_model = render_artifact_model(&fingerprinted)?;
    let request_contract = render_request_contract(&fingerprinted)?;
    for (name, rendered) in [
        (ARTIFACT_MODEL_OUTPUT, artifact_model.as_str()),
        (REQUEST_CONTRACT_OUTPUT, request_contract.as_str()),
    ] {
        if rendered.lines().next() != Some(GENERATED_HEADER) {
            return Err(PlatformErrorProjectionCodegenError::Render(format!(
                "{name} does not begin with the required generated header"
            )));
        }
    }
    Ok(vec![
        RenderedOutput {
            relative_path: ARTIFACT_MODEL_OUTPUT,
            bytes: artifact_model.into_bytes(),
        },
        RenderedOutput {
            relative_path: REQUEST_CONTRACT_OUTPUT,
            bytes: request_contract.into_bytes(),
        },
    ])
}

fn check_outputs(
    canonical_root: &Path,
    rendered: &[RenderedOutput],
) -> Result<(), PlatformErrorProjectionCodegenError> {
    for output in rendered {
        let target = resolve_output_target(canonical_root, output.relative_path, false)?;
        let actual = match fs::read(&target) {
            Ok(actual) => actual,
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
                return Err(PlatformErrorProjectionCodegenError::Missing { path: target })
            }
            Err(source) => {
                return Err(PlatformErrorProjectionCodegenError::Io {
                    path: target,
                    source,
                })
            }
        };
        if actual != output.bytes {
            return Err(PlatformErrorProjectionCodegenError::Drift { path: target });
        }
    }
    Ok(())
}

fn generate_outputs(
    canonical_root: &Path,
    rendered: Vec<RenderedOutput>,
) -> Result<(), PlatformErrorProjectionCodegenError> {
    let mut prepared = rendered
        .into_iter()
        .map(|output| {
            let target = resolve_output_target(canonical_root, output.relative_path, true)?;
            let existed = path_exists(&target)?;
            Ok(PreparedOutput {
                target,
                bytes: output.bytes,
                staged: None,
                backup: None,
                existed,
                published: false,
            })
        })
        .collect::<Result<Vec<_>, PlatformErrorProjectionCodegenError>>()?;

    if let Err(error) = stage_and_publish(&mut prepared) {
        return match cleanup_staged_and_backups(&mut prepared) {
            Ok(()) => Err(error),
            Err(cleanup) => Err(PlatformErrorProjectionCodegenError::Rollback(format!(
                "{cleanup}; original publication error: {error}"
            ))),
        };
    }
    cleanup_staged_and_backups(&mut prepared).map_err(PlatformErrorProjectionCodegenError::Rollback)
}

fn path_exists(path: &Path) -> Result<bool, PlatformErrorProjectionCodegenError> {
    match fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(source) => Err(PlatformErrorProjectionCodegenError::Io {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn stage_and_publish(
    outputs: &mut [PreparedOutput],
) -> Result<(), PlatformErrorProjectionCodegenError> {
    stage_and_publish_with(outputs, |source, target| fs::rename(source, target))
}

fn stage_and_publish_with(
    outputs: &mut [PreparedOutput],
    mut publish: impl FnMut(&Path, &Path) -> std::io::Result<()>,
) -> Result<(), PlatformErrorProjectionCodegenError> {
    for output in outputs.iter_mut() {
        let staged = unique_sibling_path(&output.target, "stage");
        write_new_file(&staged, &output.bytes)?;
        output.staged = Some(staged);
    }
    for output in outputs.iter_mut().filter(|output| output.existed) {
        let backup = unique_sibling_path(&output.target, "backup");
        fs::hard_link(&output.target, &backup).map_err(|source| {
            PlatformErrorProjectionCodegenError::Io {
                path: backup.clone(),
                source,
            }
        })?;
        output.backup = Some(backup);
    }
    for index in 0..outputs.len() {
        let staged = outputs[index]
            .staged
            .as_ref()
            .expect("every generated output was staged")
            .clone();
        if let Err(source) = publish(&staged, &outputs[index].target) {
            let publication_error = PlatformErrorProjectionCodegenError::Io {
                path: outputs[index].target.clone(),
                source,
            };
            rollback_published(outputs).map_err(|rollback| {
                PlatformErrorProjectionCodegenError::Rollback(format!(
                    "{rollback}; original publication error: {publication_error}"
                ))
            })?;
            return Err(publication_error);
        }
        outputs[index].published = true;
        outputs[index].staged = None;
    }
    Ok(())
}

fn rollback_published(outputs: &mut [PreparedOutput]) -> Result<(), String> {
    let mut failures = Vec::new();
    for output in outputs.iter_mut().rev().filter(|output| output.published) {
        let result = if let Some(backup) = output.backup.as_ref() {
            fs::rename(backup, &output.target)
        } else {
            fs::remove_file(&output.target)
        };
        if let Err(error) = result {
            failures.push(format!("{}: {error}", output.target.display()));
        } else {
            output.published = false;
            output.backup = None;
        }
    }
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("; "))
    }
}

fn cleanup_staged_and_backups(outputs: &mut [PreparedOutput]) -> Result<(), String> {
    let mut failures = Vec::new();
    for output in outputs {
        if let Some(staged) = output.staged.take() {
            if let Err(error) = fs::remove_file(&staged) {
                failures.push(format!("{}: {error}", staged.display()));
            }
        }
        if let Some(backup) = output.backup.take() {
            if let Err(error) = fs::remove_file(&backup) {
                failures.push(format!("{}: {error}", backup.display()));
            }
        }
    }
    if failures.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "failed to clean generated output transaction files: {}",
            failures.join("; ")
        ))
    }
}

fn write_new_file(path: &Path, bytes: &[u8]) -> Result<(), PlatformErrorProjectionCodegenError> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|source| PlatformErrorProjectionCodegenError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    file.write_all(bytes)
        .and_then(|()| file.sync_all())
        .map_err(|source| PlatformErrorProjectionCodegenError::Io {
            path: path.to_path_buf(),
            source,
        })
}

fn resolve_output_target(
    canonical_root: &Path,
    relative_path: &str,
    create_parent: bool,
) -> Result<PathBuf, PlatformErrorProjectionCodegenError> {
    debug_assert!(canonical_root.is_absolute());
    let relative = Path::new(relative_path);
    let parent = relative
        .parent()
        .expect("generated output has a parent directory");
    let generated_dir_name = parent
        .file_name()
        .expect("generated output parent has a final component");
    let source_dir_relative = parent
        .parent()
        .expect("generated output parent has a source directory");
    let source_dir =
        canonicalize_contained(canonical_root, &canonical_root.join(source_dir_relative))?;
    let generated_dir = source_dir.join(generated_dir_name);
    if create_parent && !generated_dir.exists() {
        fs::create_dir(&generated_dir).map_err(|source| {
            PlatformErrorProjectionCodegenError::Io {
                path: generated_dir.clone(),
                source,
            }
        })?;
    }
    let canonical_parent = if generated_dir.exists() {
        canonicalize_contained(canonical_root, &generated_dir)?
    } else {
        ensure_lexically_contained(canonical_root, &generated_dir)?;
        generated_dir
    };
    let target = canonical_parent.join(
        relative
            .file_name()
            .expect("generated output has a file name"),
    );
    match fs::symlink_metadata(&target) {
        Ok(metadata) => {
            if !metadata.file_type().is_file() || metadata.file_type().is_symlink() {
                return Err(PlatformErrorProjectionCodegenError::OutputNotRegularFile {
                    path: target,
                });
            }
            canonicalize_contained(canonical_root, &target)?;
        }
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => {}
        Err(source) => {
            return Err(PlatformErrorProjectionCodegenError::Io {
                path: target,
                source,
            })
        }
    }
    ensure_lexically_contained(canonical_root, &target)
}

fn canonicalize_contained(
    canonical_root: &Path,
    path: &Path,
) -> Result<PathBuf, PlatformErrorProjectionCodegenError> {
    let canonical =
        fs::canonicalize(path).map_err(|source| PlatformErrorProjectionCodegenError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    ensure_lexically_contained(canonical_root, &canonical)
}

fn ensure_lexically_contained(
    canonical_root: &Path,
    path: &Path,
) -> Result<PathBuf, PlatformErrorProjectionCodegenError> {
    if !path.starts_with(canonical_root) {
        return Err(
            PlatformErrorProjectionCodegenError::OutputEscapesRepository {
                path: path.to_path_buf(),
            },
        );
    }
    Ok(path.to_path_buf())
}

fn unique_sibling_path(target: &Path, purpose: &str) -> PathBuf {
    let sequence = TEMP_FILE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let file_name = target
        .file_name()
        .expect("generated output has a file name")
        .to_string_lossy();
    target.with_file_name(format!(
        ".{file_name}.skiff-codegen-{purpose}-{}-{sequence}",
        std::process::id()
    ))
}

#[cfg(test)]
#[path = "platform_error_projection_codegen/tests.rs"]
mod tests;
