[package]
name = "skiff-artifact-model"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
fuzzing = []

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
skiff-canonical-json = { path = "../canonical-json" }

[dev-dependencies]
skiff-syntax = { path = "../syntax" }

[lints]
workspace = true
