// @generated by skiff-compiler platform-error-projections; DO NOT EDIT.

use std::{fmt, str::FromStr, sync::OnceLock};

use serde::{de::Error as _, Deserialize, Deserializer, Serialize};

pub const PLATFORM_ERROR_PROJECTION_REGISTRY_ID: &str = "skiff-platform-error-projections";
pub const PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION: u32 = 1;
pub const PLATFORM_ERROR_PROJECTION_REGISTRY_FINGERPRINT: &str =
    "sha256:2c9999fba4365d136499ed6c234f0e26f091ec0a8b12e160ba2eed2f2d2ad1ea";
pub const PLATFORM_ERROR_PROJECTION_CODEC_VERSION: u32 = 1;

// Canonical public error symbols end in Error; path-derived Rust variants preserve that suffix.
#[allow(clippy::enum_variant_names)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum PlatformErrorProjectionKey {
    #[serde(rename = "config.DecodeError")]
    ConfigDecodeError,
    #[serde(rename = "std.actor.ActivationTimeoutError")]
    StdActorActivationTimeoutError,
    #[serde(rename = "std.actor.MethodInvocationTimeoutError")]
    StdActorMethodInvocationTimeoutError,
    #[serde(rename = "std.bytes.DecodeError")]
    StdBytesDecodeError,
    #[serde(rename = "std.collection.ArrayIndexOutOfBoundsError")]
    StdCollectionArrayIndexOutOfBoundsError,
    #[serde(rename = "std.collection.JsonObjectPropertyNotFoundError")]
    StdCollectionJsonObjectPropertyNotFoundError,
    #[serde(rename = "std.collection.MapKeyNotFoundError")]
    StdCollectionMapKeyNotFoundError,
    #[serde(rename = "std.db.ConflictError")]
    StdDbConflictError,
    #[serde(rename = "std.db.ConstraintError")]
    StdDbConstraintError,
    #[serde(rename = "std.db.DecodeError")]
    StdDbDecodeError,
    #[serde(rename = "std.error.InstructionLimitExceededError")]
    StdErrorInstructionLimitExceededError,
    #[serde(rename = "std.error.TimeoutError")]
    StdErrorTimeoutError,
    #[serde(rename = "std.file.FileError")]
    StdFileFileError,
    #[serde(rename = "std.http.HttpError")]
    StdHttpHttpError,
    #[serde(rename = "std.http.RequestTimeoutError")]
    StdHttpRequestTimeoutError,
    #[serde(rename = "std.json.DecodeError")]
    StdJsonDecodeError,
    #[serde(rename = "std.number.DecodeError")]
    StdNumberDecodeError,
    #[serde(rename = "std.service.ProtocolError")]
    StdServiceProtocolError,
    #[serde(rename = "std.service.ProviderUnavailableError")]
    StdServiceProviderUnavailableError,
    #[serde(rename = "std.time.DecodeError")]
    StdTimeDecodeError,
    #[serde(rename = "std.websocket.WebSocketRequestError")]
    StdWebsocketWebSocketRequestError,
}

impl PlatformErrorProjectionKey {
    pub const ALL: [Self; 21] = [
        Self::ConfigDecodeError,
        Self::StdActorActivationTimeoutError,
        Self::StdActorMethodInvocationTimeoutError,
        Self::StdBytesDecodeError,
        Self::StdCollectionArrayIndexOutOfBoundsError,
        Self::StdCollectionJsonObjectPropertyNotFoundError,
        Self::StdCollectionMapKeyNotFoundError,
        Self::StdDbConflictError,
        Self::StdDbConstraintError,
        Self::StdDbDecodeError,
        Self::StdErrorInstructionLimitExceededError,
        Self::StdErrorTimeoutError,
        Self::StdFileFileError,
        Self::StdHttpHttpError,
        Self::StdHttpRequestTimeoutError,
        Self::StdJsonDecodeError,
        Self::StdNumberDecodeError,
        Self::StdServiceProtocolError,
        Self::StdServiceProviderUnavailableError,
        Self::StdTimeDecodeError,
        Self::StdWebsocketWebSocketRequestError,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ConfigDecodeError => "config.DecodeError",
            Self::StdActorActivationTimeoutError => "std.actor.ActivationTimeoutError",
            Self::StdActorMethodInvocationTimeoutError => "std.actor.MethodInvocationTimeoutError",
            Self::StdBytesDecodeError => "std.bytes.DecodeError",
            Self::StdCollectionArrayIndexOutOfBoundsError => {
                "std.collection.ArrayIndexOutOfBoundsError"
            }
            Self::StdCollectionJsonObjectPropertyNotFoundError => {
                "std.collection.JsonObjectPropertyNotFoundError"
            }
            Self::StdCollectionMapKeyNotFoundError => "std.collection.MapKeyNotFoundError",
            Self::StdDbConflictError => "std.db.ConflictError",
            Self::StdDbConstraintError => "std.db.ConstraintError",
            Self::StdDbDecodeError => "std.db.DecodeError",
            Self::StdErrorInstructionLimitExceededError => {
                "std.error.InstructionLimitExceededError"
            }
            Self::StdErrorTimeoutError => "std.error.TimeoutError",
            Self::StdFileFileError => "std.file.FileError",
            Self::StdHttpHttpError => "std.http.HttpError",
            Self::StdHttpRequestTimeoutError => "std.http.RequestTimeoutError",
            Self::StdJsonDecodeError => "std.json.DecodeError",
            Self::StdNumberDecodeError => "std.number.DecodeError",
            Self::StdServiceProtocolError => "std.service.ProtocolError",
            Self::StdServiceProviderUnavailableError => "std.service.ProviderUnavailableError",
            Self::StdTimeDecodeError => "std.time.DecodeError",
            Self::StdWebsocketWebSocketRequestError => "std.websocket.WebSocketRequestError",
        }
    }

    pub fn parse_strict(value: &str) -> Result<Self, UnknownPlatformErrorProjectionKey> {
        value.parse()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownPlatformErrorProjectionKey {
    pub value: String,
}

impl fmt::Display for UnknownPlatformErrorProjectionKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "unknown platform error projection key {:?}",
            self.value
        )
    }
}

impl std::error::Error for UnknownPlatformErrorProjectionKey {}

impl FromStr for PlatformErrorProjectionKey {
    type Err = UnknownPlatformErrorProjectionKey;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "config.DecodeError" => Ok(Self::ConfigDecodeError),
            "std.actor.ActivationTimeoutError" => Ok(Self::StdActorActivationTimeoutError),
            "std.actor.MethodInvocationTimeoutError" => {
                Ok(Self::StdActorMethodInvocationTimeoutError)
            }
            "std.bytes.DecodeError" => Ok(Self::StdBytesDecodeError),
            "std.collection.ArrayIndexOutOfBoundsError" => {
                Ok(Self::StdCollectionArrayIndexOutOfBoundsError)
            }
            "std.collection.JsonObjectPropertyNotFoundError" => {
                Ok(Self::StdCollectionJsonObjectPropertyNotFoundError)
            }
            "std.collection.MapKeyNotFoundError" => Ok(Self::StdCollectionMapKeyNotFoundError),
            "std.db.ConflictError" => Ok(Self::StdDbConflictError),
            "std.db.ConstraintError" => Ok(Self::StdDbConstraintError),
            "std.db.DecodeError" => Ok(Self::StdDbDecodeError),
            "std.error.InstructionLimitExceededError" => {
                Ok(Self::StdErrorInstructionLimitExceededError)
            }
            "std.error.TimeoutError" => Ok(Self::StdErrorTimeoutError),
            "std.file.FileError" => Ok(Self::StdFileFileError),
            "std.http.HttpError" => Ok(Self::StdHttpHttpError),
            "std.http.RequestTimeoutError" => Ok(Self::StdHttpRequestTimeoutError),
            "std.json.DecodeError" => Ok(Self::StdJsonDecodeError),
            "std.number.DecodeError" => Ok(Self::StdNumberDecodeError),
            "std.service.ProtocolError" => Ok(Self::StdServiceProtocolError),
            "std.service.ProviderUnavailableError" => Ok(Self::StdServiceProviderUnavailableError),
            "std.time.DecodeError" => Ok(Self::StdTimeDecodeError),
            "std.websocket.WebSocketRequestError" => Ok(Self::StdWebsocketWebSocketRequestError),
            _ => Err(UnknownPlatformErrorProjectionKey {
                value: value.to_owned(),
            }),
        }
    }
}

impl fmt::Display for PlatformErrorProjectionKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformErrorProjectionDescriptor {
    key: PlatformErrorProjectionKey,
    nominal_identity: &'static str,
    entry_fingerprint: &'static str,
    codec_version: u32,
    producer_family: &'static str,
    semantic_adapter_owner: &'static str,
    public_message_policy: &'static str,
    envelope_kind: &'static str,
    fallback_policy: &'static str,
}

impl PlatformErrorProjectionDescriptor {
    pub const fn key(&self) -> PlatformErrorProjectionKey {
        self.key
    }

    pub const fn nominal_identity(&self) -> &'static str {
        self.nominal_identity
    }

    pub const fn entry_fingerprint(&self) -> &'static str {
        self.entry_fingerprint
    }

    pub const fn codec_version(&self) -> u32 {
        self.codec_version
    }

    pub const fn producer_family(&self) -> &'static str {
        self.producer_family
    }

    pub const fn semantic_adapter_owner(&self) -> &'static str {
        self.semantic_adapter_owner
    }

    pub const fn public_message_policy(&self) -> &'static str {
        self.public_message_policy
    }

    pub const fn envelope_kind(&self) -> &'static str {
        self.envelope_kind
    }

    pub const fn fallback_policy(&self) -> &'static str {
        self.fallback_policy
    }
}

static PLATFORM_ERROR_PROJECTION_REGISTRY: [PlatformErrorProjectionDescriptor; 21] = [
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::ConfigDecodeError,
        nominal_identity: "config.DecodeError",
        entry_fingerprint:
            "sha256:ffa1b591013fa33f49d8c3e36fd1f90eac8611ccd6ea6a816d251ef8e1a990f2",
        codec_version: 1,
        producer_family: "configDecode",
        semantic_adapter_owner: "runtime.boundary.config",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdActorActivationTimeoutError,
        nominal_identity: "std.actor.ActivationTimeoutError",
        entry_fingerprint:
            "sha256:c9036d5d14f9ecd9dc41fbe574837ba7dd836f4ed3c79771eb28ab0235d5187d",
        codec_version: 1,
        producer_family: "actorActivationTimeout",
        semantic_adapter_owner: "runtime.host.actor",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdActorMethodInvocationTimeoutError,
        nominal_identity: "std.actor.MethodInvocationTimeoutError",
        entry_fingerprint:
            "sha256:3364033b21bc82045bbd7a71bfc3275a4cf30e8a5934c43e9c2ea0f4cc162ccc",
        codec_version: 1,
        producer_family: "actorMethodInvocationTimeout",
        semantic_adapter_owner: "runtime.host.actor",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdBytesDecodeError,
        nominal_identity: "std.bytes.DecodeError",
        entry_fingerprint:
            "sha256:49b4ec80eb89f71a682e0b8c53a923dfbb3b4da85333775030c8bd0b1271de48",
        codec_version: 1,
        producer_family: "bytesDecode",
        semantic_adapter_owner: "runtime.boundary.bytes",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdCollectionArrayIndexOutOfBoundsError,
        nominal_identity: "std.collection.ArrayIndexOutOfBoundsError",
        entry_fingerprint:
            "sha256:00d01d71fb87454846f086cef35f5a3f0b5bef0670000daa15254fd0fe7c24cd",
        codec_version: 1,
        producer_family: "collectionArrayIndex",
        semantic_adapter_owner: "runtime.vm.collection",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdCollectionJsonObjectPropertyNotFoundError,
        nominal_identity: "std.collection.JsonObjectPropertyNotFoundError",
        entry_fingerprint:
            "sha256:71e1d94e5c10440107e0d17e58a1eef56b2485b53a1b0139245d3b5f941abc1b",
        codec_version: 1,
        producer_family: "collectionJsonObjectProperty",
        semantic_adapter_owner: "runtime.vm.collection",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdCollectionMapKeyNotFoundError,
        nominal_identity: "std.collection.MapKeyNotFoundError",
        entry_fingerprint:
            "sha256:1abcd53ea4b33e421fdd4dccfbc24c4d9b9c749ba3b6ec9abe9bebe85e431ede",
        codec_version: 1,
        producer_family: "collectionMapKey",
        semantic_adapter_owner: "runtime.vm.collection",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdDbConflictError,
        nominal_identity: "std.db.ConflictError",
        entry_fingerprint:
            "sha256:4511f1de74c636bdc0ad8049b4467ab1559754b6cb088ce768ca05f3d669aebf",
        codec_version: 1,
        producer_family: "dbConflict",
        semantic_adapter_owner: "runtime.serviceDb",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdDbConstraintError,
        nominal_identity: "std.db.ConstraintError",
        entry_fingerprint:
            "sha256:e60e20b4b08ee99594887ece6061e36959f8f78f0ad9f27dd31bf335133038cf",
        codec_version: 1,
        producer_family: "dbConstraint",
        semantic_adapter_owner: "runtime.serviceDb",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdDbDecodeError,
        nominal_identity: "std.db.DecodeError",
        entry_fingerprint:
            "sha256:ac8985db6ff4101c42a6bb671067611c0e48e241ca356837d46425fba1d6dfa8",
        codec_version: 1,
        producer_family: "dbDecode",
        semantic_adapter_owner: "runtime.serviceDb",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdErrorInstructionLimitExceededError,
        nominal_identity: "std.error.InstructionLimitExceededError",
        entry_fingerprint:
            "sha256:c0e31ea825712c96a4506771d251d91ea7d482fd3284773723b7bff66063cd88",
        codec_version: 1,
        producer_family: "instructionLimit",
        semantic_adapter_owner: "runtime.vm.executionBudget",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdErrorTimeoutError,
        nominal_identity: "std.error.TimeoutError",
        entry_fingerprint:
            "sha256:caa5a805c9f1766bb4c04c5f5c27add7ddfc956f82fc20f421f0e19cf96f68f6",
        codec_version: 1,
        producer_family: "lexicalTimeout",
        semantic_adapter_owner: "runtime.eval.timeout",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdFileFileError,
        nominal_identity: "std.file.FileError",
        entry_fingerprint:
            "sha256:7e325895d2caadb6d6b27be8cf3b36c30c025c11e6ab097316118488f2128b77",
        codec_version: 1,
        producer_family: "file",
        semantic_adapter_owner: "runtime.host.file",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdHttpHttpError,
        nominal_identity: "std.http.HttpError",
        entry_fingerprint:
            "sha256:1482750c71d3022bb47d8d594b2e5aeb1e177b2a5a1caf41125ef80709b7c141",
        codec_version: 1,
        producer_family: "http",
        semantic_adapter_owner: "runtime.host.http",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdHttpRequestTimeoutError,
        nominal_identity: "std.http.RequestTimeoutError",
        entry_fingerprint:
            "sha256:6fe26120b3ce3d94515e4b22ee4047765f705294a4bee4c55072a8db3049022f",
        codec_version: 1,
        producer_family: "httpRequestTimeout",
        semantic_adapter_owner: "runtime.host.http",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdJsonDecodeError,
        nominal_identity: "std.json.DecodeError",
        entry_fingerprint:
            "sha256:f0bf4ad3840906cc17b21453da98d49ad745f181180fb5269eca21d7be222c75",
        codec_version: 1,
        producer_family: "jsonDecode",
        semantic_adapter_owner: "runtime.boundary.json",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdNumberDecodeError,
        nominal_identity: "std.number.DecodeError",
        entry_fingerprint:
            "sha256:96d0818e3b2239613a8f7c068dad6e9f7ec30684b7ac96c670a956a0d0908cfc",
        codec_version: 1,
        producer_family: "numberDecode",
        semantic_adapter_owner: "runtime.boundary.number",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdServiceProtocolError,
        nominal_identity: "std.service.ProtocolError",
        entry_fingerprint:
            "sha256:b4634d3924d59291be0c0f25b2806c2789bbc3093a5c8bbb7dead558cf64dc1a",
        codec_version: 1,
        producer_family: "serviceProtocol",
        semantic_adapter_owner: "runtime.eval.service",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdServiceProviderUnavailableError,
        nominal_identity: "std.service.ProviderUnavailableError",
        entry_fingerprint:
            "sha256:875f4d82fb3306eead3ef84baa40a0cc82a65237d30d6dcc4f1e32ad0dd7166e",
        codec_version: 1,
        producer_family: "serviceProviderUnavailable",
        semantic_adapter_owner: "runtime.eval.service",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdTimeDecodeError,
        nominal_identity: "std.time.DecodeError",
        entry_fingerprint:
            "sha256:203bb25750e7740f404540d31a4c86c9de8b1177e6a71b4249f95a5a50130a61",
        codec_version: 1,
        producer_family: "timeDecode",
        semantic_adapter_owner: "runtime.boundary.time",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
    PlatformErrorProjectionDescriptor {
        key: PlatformErrorProjectionKey::StdWebsocketWebSocketRequestError,
        nominal_identity: "std.websocket.WebSocketRequestError",
        entry_fingerprint:
            "sha256:72c5df02a2e86f1c45aeac73188e7236b488dbebe29669677bbb92b9bd2ec071",
        codec_version: 1,
        producer_family: "webSocketRequest",
        semantic_adapter_owner: "runtime.host.websocket",
        public_message_policy: "semanticAdapterSanitized",
        envelope_kind: "platformError",
        fallback_policy: "fixedInternalErrorBeforeEnvelope",
    },
];

pub fn platform_error_projection_registry() -> &'static [PlatformErrorProjectionDescriptor] {
    &PLATFORM_ERROR_PROJECTION_REGISTRY
}

pub const fn platform_error_projection_descriptor(
    key: PlatformErrorProjectionKey,
) -> &'static PlatformErrorProjectionDescriptor {
    match key {
        PlatformErrorProjectionKey::ConfigDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[0],
        PlatformErrorProjectionKey::StdActorActivationTimeoutError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[1]
        }
        PlatformErrorProjectionKey::StdActorMethodInvocationTimeoutError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[2]
        }
        PlatformErrorProjectionKey::StdBytesDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[3],
        PlatformErrorProjectionKey::StdCollectionArrayIndexOutOfBoundsError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[4]
        }
        PlatformErrorProjectionKey::StdCollectionJsonObjectPropertyNotFoundError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[5]
        }
        PlatformErrorProjectionKey::StdCollectionMapKeyNotFoundError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[6]
        }
        PlatformErrorProjectionKey::StdDbConflictError => &PLATFORM_ERROR_PROJECTION_REGISTRY[7],
        PlatformErrorProjectionKey::StdDbConstraintError => &PLATFORM_ERROR_PROJECTION_REGISTRY[8],
        PlatformErrorProjectionKey::StdDbDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[9],
        PlatformErrorProjectionKey::StdErrorInstructionLimitExceededError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[10]
        }
        PlatformErrorProjectionKey::StdErrorTimeoutError => &PLATFORM_ERROR_PROJECTION_REGISTRY[11],
        PlatformErrorProjectionKey::StdFileFileError => &PLATFORM_ERROR_PROJECTION_REGISTRY[12],
        PlatformErrorProjectionKey::StdHttpHttpError => &PLATFORM_ERROR_PROJECTION_REGISTRY[13],
        PlatformErrorProjectionKey::StdHttpRequestTimeoutError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[14]
        }
        PlatformErrorProjectionKey::StdJsonDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[15],
        PlatformErrorProjectionKey::StdNumberDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[16],
        PlatformErrorProjectionKey::StdServiceProtocolError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[17]
        }
        PlatformErrorProjectionKey::StdServiceProviderUnavailableError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[18]
        }
        PlatformErrorProjectionKey::StdTimeDecodeError => &PLATFORM_ERROR_PROJECTION_REGISTRY[19],
        PlatformErrorProjectionKey::StdWebsocketWebSocketRequestError => {
            &PLATFORM_ERROR_PROJECTION_REGISTRY[20]
        }
    }
}

pub fn platform_error_projection_descriptor_by_key(
    key: &str,
) -> Option<&'static PlatformErrorProjectionDescriptor> {
    PlatformErrorProjectionKey::parse_strict(key)
        .ok()
        .map(platform_error_projection_descriptor)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PlatformErrorProjectionRegistryRef {
    registry_id: String,
    registry_version: u32,
    fingerprint: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct PlatformErrorProjectionRegistryRefWire {
    registry_id: String,
    registry_version: u32,
    fingerprint: String,
}

impl PlatformErrorProjectionRegistryRef {
    pub fn registry_id(&self) -> &str {
        &self.registry_id
    }

    pub const fn registry_version(&self) -> u32 {
        self.registry_version
    }

    pub fn fingerprint(&self) -> &str {
        &self.fingerprint
    }
}

impl<'de> Deserialize<'de> for PlatformErrorProjectionRegistryRef {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let wire = PlatformErrorProjectionRegistryRefWire::deserialize(deserializer)?;
        let descriptor = Self {
            registry_id: wire.registry_id,
            registry_version: wire.registry_version,
            fingerprint: wire.fingerprint,
        };
        validate_platform_error_projection_registry_ref_shape(&descriptor)
            .map_err(|error| D::Error::custom(error.to_string()))?;
        Ok(descriptor)
    }
}

pub fn current_platform_error_projection_registry_ref(
) -> &'static PlatformErrorProjectionRegistryRef {
    static CURRENT: OnceLock<PlatformErrorProjectionRegistryRef> = OnceLock::new();
    CURRENT.get_or_init(|| PlatformErrorProjectionRegistryRef {
        registry_id: PLATFORM_ERROR_PROJECTION_REGISTRY_ID.to_owned(),
        registry_version: PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
        fingerprint: PLATFORM_ERROR_PROJECTION_REGISTRY_FINGERPRINT.to_owned(),
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlatformErrorProjectionRegistryRefValidationError {
    RegistryId,
    RegistryVersion,
    FingerprintGrammar,
    CurrentFingerprintMismatch,
}

impl fmt::Display for PlatformErrorProjectionRegistryRefValidationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::RegistryId => "platform error projection registryId is invalid",
            Self::RegistryVersion => "platform error projection registryVersion is invalid",
            Self::FingerprintGrammar => "platform error projection fingerprint grammar is invalid",
            Self::CurrentFingerprintMismatch => {
                "platform error projection fingerprint is not current"
            }
        })
    }
}

impl std::error::Error for PlatformErrorProjectionRegistryRefValidationError {}

pub fn validate_platform_error_projection_registry_ref_shape(
    descriptor: &PlatformErrorProjectionRegistryRef,
) -> Result<(), PlatformErrorProjectionRegistryRefValidationError> {
    if descriptor.registry_id() != PLATFORM_ERROR_PROJECTION_REGISTRY_ID {
        return Err(PlatformErrorProjectionRegistryRefValidationError::RegistryId);
    }
    if descriptor.registry_version() != PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION {
        return Err(PlatformErrorProjectionRegistryRefValidationError::RegistryVersion);
    }
    if !is_sha256_fingerprint(descriptor.fingerprint()) {
        return Err(PlatformErrorProjectionRegistryRefValidationError::FingerprintGrammar);
    }
    Ok(())
}

pub fn validate_current_platform_error_projection_registry_ref(
    descriptor: &PlatformErrorProjectionRegistryRef,
) -> Result<(), PlatformErrorProjectionRegistryRefValidationError> {
    validate_platform_error_projection_registry_ref_shape(descriptor)?;
    if descriptor.fingerprint() != PLATFORM_ERROR_PROJECTION_REGISTRY_FINGERPRINT {
        return Err(PlatformErrorProjectionRegistryRefValidationError::CurrentFingerprintMismatch);
    }
    Ok(())
}

fn is_sha256_fingerprint(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|digest| {
        digest.len() == 64
            && digest
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    })
}

pub fn assert_platform_error_projection_generated_surface() {
    assert_eq!(platform_error_projection_registry().len(), 21);
    for (index, descriptor) in platform_error_projection_registry().iter().enumerate() {
        assert_eq!(descriptor.key(), PlatformErrorProjectionKey::ALL[index]);
        assert_eq!(descriptor.key().as_str(), descriptor.nominal_identity());
        let parsed = PlatformErrorProjectionKey::parse_strict(descriptor.key().as_str())
            .expect("generated descriptor key must parse");
        assert_eq!(parsed, descriptor.key());
        assert!(std::ptr::eq(
            platform_error_projection_descriptor(parsed),
            descriptor
        ));
        assert!(std::ptr::eq(
            platform_error_projection_descriptor_by_key(descriptor.key().as_str())
                .expect("generated descriptor string key must resolve"),
            descriptor
        ));
        assert_eq!(
            descriptor.codec_version(),
            PLATFORM_ERROR_PROJECTION_CODEC_VERSION
        );
        assert!(is_sha256_fingerprint(descriptor.entry_fingerprint()));
        assert!(!descriptor.producer_family().is_empty());
        assert!(!descriptor.semantic_adapter_owner().is_empty());
        assert!(!descriptor.public_message_policy().is_empty());
        assert!(!descriptor.envelope_kind().is_empty());
        assert!(!descriptor.fallback_policy().is_empty());
    }
    for pair in platform_error_projection_registry().windows(2) {
        assert!(pair[0].key().as_str() < pair[1].key().as_str());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_surface_is_exact_and_unversioned() {
        assert_platform_error_projection_generated_surface();
        for key in PlatformErrorProjectionKey::ALL {
            assert!(!key.as_str().split('.').any(|segment| {
                segment.strip_prefix('v').is_some_and(|digits| {
                    !digits.is_empty() && digits.bytes().all(|byte| byte.is_ascii_digit())
                })
            }));
        }
    }

    #[test]
    fn registry_ref_deserialization_validates_general_shape() {
        let alternate_fingerprint = format!("sha256:{}", "0".repeat(64));
        let alternate: PlatformErrorProjectionRegistryRef =
            serde_json::from_value(serde_json::json!({
                "registryId": PLATFORM_ERROR_PROJECTION_REGISTRY_ID,
                "registryVersion": PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
                "fingerprint": alternate_fingerprint,
            }))
            .unwrap();
        assert_eq!(
            alternate.registry_id(),
            PLATFORM_ERROR_PROJECTION_REGISTRY_ID
        );
        assert_eq!(
            alternate.registry_version(),
            PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION
        );
        assert_eq!(
            alternate.fingerprint(),
            format!("sha256:{}", "0".repeat(64))
        );
        assert_eq!(
            validate_current_platform_error_projection_registry_ref(&alternate),
            Err(PlatformErrorProjectionRegistryRefValidationError::CurrentFingerprintMismatch)
        );

        let valid_fingerprint = format!("sha256:{}", "0".repeat(64));
        for invalid in [
            serde_json::json!({
                "registryId": "other",
                "registryVersion": PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
                "fingerprint": valid_fingerprint,
            }),
            serde_json::json!({
                "registryId": PLATFORM_ERROR_PROJECTION_REGISTRY_ID,
                "registryVersion": 2,
                "fingerprint": valid_fingerprint,
            }),
            serde_json::json!({
                "registryId": PLATFORM_ERROR_PROJECTION_REGISTRY_ID,
                "registryVersion": PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
                "fingerprint": format!("sha256:{}", "A".repeat(64)),
            }),
            serde_json::json!({
                "registryId": PLATFORM_ERROR_PROJECTION_REGISTRY_ID,
                "registryVersion": PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
                "fingerprint": valid_fingerprint,
                "unexpected": true,
            }),
        ] {
            assert!(serde_json::from_value::<PlatformErrorProjectionRegistryRef>(invalid).is_err());
        }
    }

    #[test]
    fn current_registry_ref_is_one_exact_read_only_singleton() {
        let current = current_platform_error_projection_registry_ref();
        assert!(std::ptr::eq(
            current,
            current_platform_error_projection_registry_ref()
        ));
        assert_eq!(current.registry_id(), PLATFORM_ERROR_PROJECTION_REGISTRY_ID);
        assert_eq!(
            current.registry_version(),
            PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION
        );
        assert_eq!(
            current.fingerprint(),
            PLATFORM_ERROR_PROJECTION_REGISTRY_FINGERPRINT
        );
        validate_current_platform_error_projection_registry_ref(current).unwrap();
        assert_eq!(
            serde_json::to_value(current).unwrap(),
            serde_json::json!({
                "registryId": PLATFORM_ERROR_PROJECTION_REGISTRY_ID,
                "registryVersion": PLATFORM_ERROR_PROJECTION_REGISTRY_VERSION,
                "fingerprint": PLATFORM_ERROR_PROJECTION_REGISTRY_FINGERPRINT,
            })
        );
    }
}
