[package]
name = "skiff-runtime-package-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
skiff-artifact-model = { path = "../../artifact-model" }
skiff-runtime-linker = { path = "../linker" }
skiff-runtime-loader = { path = "../loader" }

[dev-dependencies]
skiff-artifact-identity = { path = "../../artifact-identity" }
skiff-deployment = { path = "../../deployment" }

[lints]
workspace = true
