[package]
name = "skiff-runtime-deployment-image"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
skiff-artifact-model = { path = "../../artifact-model" }
tokio = { version = "1.44", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.44", features = ["macros", "time"] }

[lints]
workspace = true
